sudo: required
services:
  - docker

before_install:
  - docker build -t ikholwadia/reacttest -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true ikholwadia/reacttest npm test

after_success:
  - dockerbuild -t ikholwadia/multi-client ./client
   - dockerbuild -t ikholwadia/multi-nginx ./nginx
  - dockerbuild -t ikholwadia/multi-server ./server
  - dockerbuild -t ikholwadia/multi-worker ./worker

  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  - docker push ikholwadia/multi-client
  - docker push ikholwadia/multi-nginx
  - docker push ikholwadia/multi-server
  - docker push ikholwadia/multi-worker

